apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/component: frontend
    {{- include "ehs-helm.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if and (eq .Values.frontend.service.type "ClusterIP") .Values.frontend.service.clusterIP }}
  clusterIP: {{ .Values.frontend.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.frontend.service.type "LoadBalancer") .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    {{- include "ehs-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.javaService.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.javaService.name }}
    app.kubernetes.io/component: java-service
    {{- include "ehs-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.javaService.service.type }}
  ports:
    - port: {{ .Values.javaService.service.port }}
      targetPort: {{ .Values.javaService.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.javaService.grpc.enabled }}
    - port: {{ .Values.javaService.grpc.port }}
      targetPort: {{ .Values.javaService.grpc.port }}
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.javaService.name }}
    {{- include "ehs-helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonService.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.pythonService.name }}
    app.kubernetes.io/component: python-service
    {{- include "ehs-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pythonService.service.type }}
  ports:
    - port: {{ .Values.pythonService.service.port }}
      targetPort: {{ .Values.pythonService.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.pythonService.grpc.enabled }}
    - port: {{ .Values.pythonService.grpc.port }}
      targetPort: {{ .Values.pythonService.grpc.port }}
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.pythonService.name }}
    {{- include "ehs-helm.selectorLabels" . | nindent 4 }}
