# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.infrastructure.grpc.proto import ehs_pb2 as ehs__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ehs_clean_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EhsAiServiceStub(object):
    """==================== 服务定义 ====================

    EHS AI 服务 - 提供 AI 能力
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ehs.EhsAiService/HealthCheck',
                request_serializer=ehs__clean__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ClassifyRisk = channel.unary_unary(
                '/ehs.EhsAiService/ClassifyRisk',
                request_serializer=ehs__clean__pb2.RiskClassificationRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.RiskClassificationResponse.FromString,
                _registered_method=True)
        self.GenerateResponse = channel.unary_unary(
                '/ehs.EhsAiService/GenerateResponse',
                request_serializer=ehs__clean__pb2.ResponseGenerationRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.ResponseGenerationResponse.FromString,
                _registered_method=True)
        self.AnalyzeAlert = channel.unary_unary(
                '/ehs.EhsAiService/AnalyzeAlert',
                request_serializer=ehs__clean__pb2.AlertAnalysisRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.AlertAnalysisResponse.FromString,
                _registered_method=True)
        self.GetTermEmbedding = channel.unary_unary(
                '/ehs.EhsAiService/GetTermEmbedding',
                request_serializer=ehs__clean__pb2.TermEmbeddingRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.TermEmbeddingResponse.FromString,
                _registered_method=True)
        self.GetBatchEmbeddings = channel.unary_unary(
                '/ehs.EhsAiService/GetBatchEmbeddings',
                request_serializer=ehs__clean__pb2.BatchEmbeddingRequest.SerializeToString,
                response_deserializer=ehs__clean__pb2.BatchEmbeddingResponse.FromString,
                _registered_method=True)


class EhsAiServiceServicer(object):
    """==================== 服务定义 ====================

    EHS AI 服务 - 提供 AI 能力
    """

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyRisk(self, request, context):
        """风险分级 - 分析文本风险等级
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateResponse(self, request, context):
        """指令微调生成 - 基于上下文生成响应
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAlert(self, request, context):
        """告警分析 - 分析告警事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTermEmbedding(self, request, context):
        """术语 Embedding - 获取术语向量表示
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchEmbeddings(self, request, context):
        """批量术语 Embedding - 批量获取术语向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EhsAiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ehs__clean__pb2.HealthCheckRequest.FromString,
                    response_serializer=ehs__clean__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ClassifyRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyRisk,
                    request_deserializer=ehs__clean__pb2.RiskClassificationRequest.FromString,
                    response_serializer=ehs__clean__pb2.RiskClassificationResponse.SerializeToString,
            ),
            'GenerateResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=ehs__clean__pb2.ResponseGenerationRequest.FromString,
                    response_serializer=ehs__clean__pb2.ResponseGenerationResponse.SerializeToString,
            ),
            'AnalyzeAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAlert,
                    request_deserializer=ehs__clean__pb2.AlertAnalysisRequest.FromString,
                    response_serializer=ehs__clean__pb2.AlertAnalysisResponse.SerializeToString,
            ),
            'GetTermEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTermEmbedding,
                    request_deserializer=ehs__clean__pb2.TermEmbeddingRequest.FromString,
                    response_serializer=ehs__clean__pb2.TermEmbeddingResponse.SerializeToString,
            ),
            'GetBatchEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchEmbeddings,
                    request_deserializer=ehs__clean__pb2.BatchEmbeddingRequest.FromString,
                    response_serializer=ehs__clean__pb2.BatchEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ehs.EhsAiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ehs.EhsAiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EhsAiService(object):
    """==================== 服务定义 ====================

    EHS AI 服务 - 提供 AI 能力
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/HealthCheck',
            ehs__clean__pb2.HealthCheckRequest.SerializeToString,
            ehs__clean__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/ClassifyRisk',
            ehs__clean__pb2.RiskClassificationRequest.SerializeToString,
            ehs__clean__pb2.RiskClassificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/GenerateResponse',
            ehs__clean__pb2.ResponseGenerationRequest.SerializeToString,
            ehs__clean__pb2.ResponseGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/AnalyzeAlert',
            ehs__clean__pb2.AlertAnalysisRequest.SerializeToString,
            ehs__clean__pb2.AlertAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTermEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/GetTermEmbedding',
            ehs__clean__pb2.TermEmbeddingRequest.SerializeToString,
            ehs__clean__pb2.TermEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ehs.EhsAiService/GetBatchEmbeddings',
            ehs__clean__pb2.BatchEmbeddingRequest.SerializeToString,
            ehs__clean__pb2.BatchEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
